#:schema node_modules/wrangler/config-schema.json
name = "vault-block"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

# Automatically place your workloads in an optimal location to minimize latency.
# If you are running back-end logic in a Pages Function, running it closer to your back-end infrastructure
# rather than the end user may result in better performance.
# Docs: https://developers.cloudflare.com/pages/functions/smart-placement/#smart-placement
[placement]
mode = "smart"

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/pages/functions/bindings/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/pages/functions/bindings/#secrets
[vars]
### never put secrets here ###
VITE_MAX_VAULTS = 5
NOTION_API_VERSION = "2022-06-28"

# Bind the Workers AI model catalog. Run machine learning models, powered by serverless GPUs, on Cloudflare’s global network
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#workers-ai
# [ai]
# binding = "AI"

# Bind a D1 database. D1 is Cloudflare’s native serverless SQL database.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#d1-databases
# [[d1_databases]]
# binding = "MY_DB"
# database_name = "my-database"
# database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"

[[kv_namespaces]]
binding = "VAULT_BLOCK_KV"
id = "bf7b6d2d323f481991c707846c6d3d42"

[[d1_databases]]
binding = "DB"
database_name = "vault-block"
database_id = "02d4132a-cbe4-4c98-b42c-c0b4eb7a16e1"
migrations_dir = "functions/src/db/migrations"

# Bind a Durable Object. Durable objects are a scale-to-zero compute primitive based on the actor model.
# Durable Objects can live for as long as needed. Use these when you need a long-running "server", such as in realtime apps.
# Docs: https://developers.cloudflare.com/workers/runtime-apis/durable-objects
# [[durable_objects.bindings]]
# name = "MY_DURABLE_OBJECT"
# class_name = "MyDurableObject"
# script_name = 'my-durable-object'

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#kv-namespaces
# KV Example:
# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# Bind a Queue producer. Use this binding to schedule an arbitrary task that may be processed later by a Queue consumer.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#queue-producers
# [[queues.producers]]
# binding = "MY_QUEUE"
# queue = "my-queue"

# Bind an R2 Bucket. Use R2 to store arbitrarily large blobs of data, such as files.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#r2-buckets
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# Bind another Worker service. Use this binding to call another Worker without network overhead.
# Docs: https://developers.cloudflare.com/pages/functions/bindings/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

# To use different bindings for preview and production environments, follow the examples below.
# When using environment-specific overrides for bindings, ALL bindings must be specified on a per-environment basis.
# Docs: https://developers.cloudflare.com/pages/functions/wrangler-configuration#environment-specific-overrides

######## PREVIEW environment config ########

[env.preview.vars]
### never put secrets here ###
VITE_MAX_VAULTS = 5
NOTION_API_VERSION = "2022-06-28"

[[env.preview.kv_namespaces]]
binding = "VAULT_BLOCK_KV"
id = "bf7b6d2d323f481991c707846c6d3d42"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "vault-block-dev"
database_id = "02d4132a-cbe4-4c98-b42c-c0b4eb7a16e1"
migrations_dir = "functions/src/db/migrations"

######## PRODUCTION environment config ########

[env.production.vars]
### never put secrets here ###
VITE_MAX_VAULTS = 5
NOTION_API_VERSION = "2022-06-28"

[[env.production.kv_namespaces]]
binding = "VAULT_BLOCK_KV"
id = "560480b4cb67435eba96664bb77bac6b"

[[env.production.d1_databases]]
binding = "DB"
database_name = "vault-block-prod"
database_id = "35aeb56b-08ba-4298-94de-5694821c13f3"
migrations_dir = "functions/src/db/migrations"
